baseurl = "https://ccg.github.io"
languageCode = "en-us"
title = "Chad Glendenin"
theme = "hugo-lithium"
googleAnalytics = "UA-35516212-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ccg"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ccglen"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    # Apparently somehow this is hardcoded to 'static/images/'.
    # The subdirectory cannot be named anything other than `images/`.
    url = "ccg.png"
    width = 50
    height = 50
    alt = "Logo"

